name: picbox
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  material_design_icons_flutter: ^3.4.4795
  ubuntu_font_flutter: ^0.0.1
  flare_flutter: ^1.8.3
  transparent_image: ^1.0.0

  # localizations
  flutter_localizations:
    sdk: flutter
  devicelocale: ^0.2.1

  # bloc
  flutter_bloc: ^3.1.0

  # network
  chopper: ^3.0.1+1
  json_annotation: ^3.0.1

  # db
  shared_preferences: ^0.5.6
  flutter_secure_storage: ^3.3.1+1

  # ui
  native_device_orientation: ^0.3.0
  sms_autofill: ^1.1.1

  # convert
  built_value: ^7.0.8
  built_collection: ^4.3.2

  # compare
  equatable: ^1.0.2

  # data
  logger: ^0.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  chopper_generator:
    git:
      url: git://github.com/windrunner414/chopper.git
      path: chopper_generator
  json_serializable: ^3.2.5

flutter:
  uses-material-design: true
  assets:
    - resources/flare/
    - resources/lang/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf
