name: picbox
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^3.2.3695
  flutter_bloc: ^2.0.0
  native_device_orientation: ^0.3.0
  equatable: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
