name: picbox
description: A new Flutter project.
version: 0.0.1+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^3.2.3695
  flutter_bloc: ^2.0.0
  native_device_orientation: ^0.3.0
  equatable: ^0.6.1
  ubuntu_font_flutter: ^0.0.1
  flare_flutter: ^1.8.0
  easy_localization: ^1.3.1
  devicelocale: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - resources/flare/
    - resources/langs/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-R.ttf
        - asset: packages/ubuntu_font_flutter/Ubuntu-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/Ubuntu-BI.ttf
          weight: 700
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-L.ttf
          weight: 300
        - asset: packages/ubuntu_font_flutter/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: packages/ubuntu_font_flutter/Ubuntu-M.ttf
          weight: 500
        - asset: packages/ubuntu_font_flutter/Ubuntu-MI.ttf
          weight: 500
          style: italic
    - family: Ubuntu Mono
      fonts:
        - asset: packages/ubuntu_font_flutter/UbuntuMono-R.ttf
        - asset: packages/ubuntu_font_flutter/UbuntuMono-RI.ttf
          style: italic
        - asset: packages/ubuntu_font_flutter/UbuntuMono-B.ttf
          weight: 700
        - asset: packages/ubuntu_font_flutter/UbuntuMono-BI.ttf
          weight: 700
          style: italic
    - family: Ubuntu Condensed
      fonts:
        - asset: packages/ubuntu_font_flutter/Ubuntu-C.ttf
