name: android
on: [push]
jobs:
  build:
    name: Build and publish
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, '[ignore]')"
    steps:
      - name: Cloning
        uses: actions/checkout@v2
      - name: Installing Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Installing Flutter (beta branch)
        uses: subosito/flutter-action@v1
        with:
          channel: "beta"
      - name: Installing dependencies
        run: flutter pub get
      - name: Building Android
        run: flutter build apk --release --split-per-abi
      - if: "!contains(github.event.head_commit.message, '[publish]')"
        name: Uploading artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/app/outputs/apk/release

      - if: "contains(github.event.head_commit.message, '[publish]')"
        name: Publishing build in release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
