name: Build for Android
on: [push]
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ignore]')"
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        uses: steebchen/flutter@v1.0.0
        with:
          args: pub get
      - name: Building APK
        uses: steebchen/flutter@v1.0.0
        with:
          args: build apk --release --split-per-abi
      - if: "!contains(github.event.head_commit.message, '[publish]')"
        name: Uploading artifacts
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: build/app/outputs/apk/release

      - if: "contains(github.event.head_commit.message, '[publish]')"
        name: Publishing build in release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          token: ${{ secrets.TOKEN }}
