on: push
if: "contains(github.event.head_commit.message, 'ci build')"
name: Build Release
jobs:
  build:
    name: Android
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - run: flutter pub get
    - run: flutter build apk --release --split-per-abi
    - name: Upload release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/apk/*.apk"
        token: ${{ secrets.TOKEN }}