on: push
name: Build current branch
jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[build]')"
    steps:
      - name: Cloning
        uses: actions/checkout@v1
      - name: Installing Java
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: Installing Flutter (stable branch)
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Installing dependencies
        run: flutter pub get
      - name: Analyzing Dart code
        run: flutter analyze
      - name: Building Android
        run: flutter build apk --release --split-per-abi
      - name: Publishing
        uses: actions/upload-artifact@v1
        with:
          title: app-artifacts
            - name: "Android"
              files: build/app/outputs/apk/release/*.apk